---
title: "My First Official Map"
author: "Nicole Ayala"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

# *Loading the libraries*
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

### load libraries ###
library(tidyverse)
library(dplyr)
library(tidyr)
library(here)
library(ggplot2)
library(mapproj)
library(maps)
library(mapdata)
library(tidytuesdayR)

```
# *Inspecting the data*
```{r}
### inspect the data ###
meteorites<-read.csv(here("Week_07","Data","meteorites.csv")) # Read in data on meteorites
glimpse(meteorites) # looking at my data
View(meteorites)



```
# Making a Map of the Amount of __Meteorites__ Seen in the Past *30 Years*
```{r}
# Time to look at the meteorites data
head(meteorites)               

world<-map_data("world") # get data for the entire world
head(world)

states<-map_data("state") 
# get data for states
head(states)

usa<-map_data("usa") # get data for the USA
head(usa)

```


```{r}
meteor<-meteorites %>%
  filter(mass>"2000.0" & fall != "fell") %>% # filter out mass less than 2000 lbs
  mutate(after_1993=ifelse(year>1973,"After 1993","Before 1993")) # only look at the last 30 years

View(meteor)
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, # x is always LONGITUDE
                   y = lat, # y is always LATITUTDE
                   group = group ),
               fill = "white") + # ALWAYS SET GROUP = GROUP
               
  geom_point(data= meteor,
             aes(x= long,
                 y= lat),
             color = "burlywood4",
             alpha = 0.3) +
  guides(fill = FALSE) + # to not get hundreds of colors 
  facet_wrap(~fall) +
   labs(x= "Longitude",
       y= "Latitude",
       title= "Meteorites Seen Throughout the World Over 2000 Pounds")+
  theme_bw() + # makes it look simple and clean with white grid lines
  theme(panel.background = element_rect(fill = "dodgerblue4")) 

ggsave(here("Week_07","Output","MeteorsAroundtheWorld.pdf"))
```
