___
title: "HW Lab 8 Assignment"
author: "Nicole Ayala"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```


### Functional programming

- Step 1: Name the function
- Step 2: Put in the equation
- Step 3: Decide what the arguments are
- Step 4: Decide what is being returned

```{r}
### Load in the Library

library(tidyverse)
library(here)
library(hrbrthemes) 
library(ggplot2)
library(rlang)
```

# Here is my First Function
```{r}
### Load in the Data
auto <- read.csv(here("Week_09", "Data", "auto-mpg.csv")) # one of my datasets

cars <- mtcars # my dataset
#View(mtcars)

# I will be converting miles per gallon to kilometers per liter as this was a great way to measure that a vehicle can travel while consuming a certain amount of liters of gas per km (one liter of gas) km/L is a measurement of fuel economy
mpgtokmpl <- function(mpg) {
kmpl <- (mpg * 0.425144) #  this function converts a value in miles per gallon to kilometers per liter
  return(kmpl) # return the kmpl value
}
```


```{r}
kmplcars <- cars %>% # piping mtcars to new name showing that I will be converting m/g to km/l with function created
  mutate(kmpl = mpgtokmpl(mpg)) # mutating name to mpgtokmpl from kmpl

kmplauto <- auto %>% # piping auto to new name showing that I will be converting m/g to km/l with function created
  mutate(kmpl = mpgtokmpl(mpg)) #mutating name to mpgtokmpl from kmpl

```

### Here is my Second Function


```{r}

mobileplot<-function(data, x, y)
  
  ggplot(data,
       aes(x = {{x}}, y = {{y}}))+
  geom_point()+
  labs(x = "Miles per Gallon", y = "Acceleration", title = "Correlation of the Acceleration within Cars and their Amount of Gallon Used") + # title and subtitles + x and y axes
  theme(panel.grid.major = element_blank(),# keeps background blank (maj/min)
        panel.grid.minor = element_blank()) +
  theme(axis.title = element_text(size = 30, color = "navyblue"),
  panel.background = element_rect(fill = "white"))
  # background color is white



```
 
```{r}
mobileplot(data = auto, x = mpg, y = acceleration)+
  geom_point() +
  theme_minimal()+
  labs(x = "Miles per Gallon", y = "Acceleration", title = "The Acceleration within Auto Mobiles and their Amount of Gallons Used") + # title  + x and y axes
  theme(panel.grid.major = element_blank(),# keeps background blank (maj/min)
        panel.grid.minor = element_blank()) +
  theme(axis.title = element_text(size = 40, color = "navyblue"),
  panel.background = element_rect(fill = "white")) # background color

ggsave(here("Week_09","Output","automobileplot.png"))
```


```{r}
mobileplot(data = cars, x = mpg, y = cyl)+
  geom_point() +
  theme_minimal()+
  labs(x = "Miles per Gallon", y = "Cylinders", title = "The Number of Cylinders within Cars and their Amount of Gallons Used") + # title  + x and y axes
  theme(panel.grid.major = element_blank(),# keeps background blank (maj/min)
        panel.grid.minor = element_blank()) +
  theme(axis.title = element_text(size = 40, color = "plum4"),
  panel.background = element_rect(fill = "white")) # background color

ggsave(here("Week_09","Output","carmobileplot.png"))
```
