---
title: "LabAssignment8b"
author: "Nicole Ayala"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

## Lab Assignment for Week 8b: Functional programming

- Step 1: Name the function
- Step 2: Put in the equation
- Step 3: Decide what the arguments are
- Step 4: Decide what is being returned

```{r}
### Load in the Library

library(tidyverse)
library(here)
library(RColorBrewer) 
library(rlang)
library(ggplot2)
### Load in the Data
auto <- read.csv(here("Week_09", "Data", "auto-mpg.csv")) 
# my data set
 cars <- mtcars # my dataset
#View(mtcars)

# I will be converting miles per gallon to kilometers per liter as this was a great way to measure that a vehicle can travel while consuming a certain amount of liters of gas per km (one liter of gas) km/L is a measurement of fuel economy

mpgtokmpl <- function(mpg) {
kmpl <- (mpg * 0.425144) #  this function converts a value in miles per gallon to kilometers per liter
  return(kmpl) # return the kmpl value
}
```
```{r}
kmplcars <- cars %>% # piping mtcars to new name showing that I will be converting m/g to km/l with function created
  mutate(kmpl = mpgtokmpl(mpg))

kmplauto <- auto %>%
  mutate(kmpl = mpgtokmpl(mpg))
#View(kmplauto)
#View(kmplcars)


```

## Making a Plot Function

### Ordered Plot
```{r}
carsplot <- function(data = cars, x, y, order = TRUE) {
  
if(order==TRUE){# I can order the bar plot if "if" is set to TRUE
ggplot(data = cars, 
       aes(x = reorder({{x}}, -{{y}}), y = {{y}}))+
# ordering my axes in a particular way that makes sense
   geom_bar(stat="identity",  # better than bin
            fill = "beige",# filling color inside of the bar
            color = "orange",# outline color of the bars
            width = 0.8)+ #  width of the bars
    theme_minimal()
}
else{# if "if" is set to FALSE then bar plot will not be ordered
ggplot(data = cars, 
       aes(x = {{x}}, y = {{y}}))+
   geom_bar(stat="identity", 
         fill = "beige",# filling color inside of the bar
            color = "orange",# outline color of the bars
            width = 0.8)+#  width of the bars
    theme_minimal()
}
}
```
### Disordered Plot 
```{r carsdisorder}
carsplot(data, x = mpg, y = hp, order = FALSE)+
    labs(x = " Miles per Gallon (mpg)", # updates x name                       
       y = "Horse Power", # updates y name
       title = " Horse Power Exerted at a Certain Miles Per Gallon") # title name

ggsave(here("Week_09","Output","disorderedplot.png"))

```
### Ordered Plot
```{r carsorder}
carsplot(data, x = mpg, y = hp, order = TRUE)+
  labs(x = " Miles per Gallon (mpg)", # update x name                         
       y = "Horse Power", # update y name
       title = " Horse Power Exerted at a Certain Miles Per Gallon") # title name
ggsave(here("Week_09","Output","orderedplot.png"))
```

