---
title: "LabAssignment8b"
author: "Nicole Ayala"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

## Lab Assignment for Week 8b: Functional programming

- Step 1: Name the function
- Step 2: Put in the equation
- Step 3: Decide what the arguments are
- Step 4: Decide what is being returned

## Making a Plot Function

```{r}
data(mtcars)

library(hrbrthemes) # for the PNW color palette 
library(rlang)
library(ggplot2)

carplot<-function(data = mtcars, x, y){ 
pnwc<-pnw_palette("Bay",6, type = "continuous") # my color palette for 6 cars
ggplot(data, aes(x = {{wt}}, y = {{mpg}} , color = hp))+
  geom_histogram()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Horse Power", values=pnwc)+   # use pretty colors and change the legend title
  theme_bw()
}
pnwc<-hrbrthemes::("",6, type = "continuous") # my color palette 
if(lines==TRUE){
ggplot(data, aes(x = {{wt}}, y = {{mpg}} , color = hp))+
  geom_histogram()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Horse Power", values=pnwc)+   # use pretty colors and change the legend title
  theme_bw()
}
else{
ggplot(data, aes(x = {{x}}, y = {{y}} , color = hp))+
  geom_histogram()+
  scale_color_manual("Horse Power", values=pnwc)+   # use pretty colors and change the legend title
  theme_bw()

carplot(x = wt, y = mpg)
```


## Making a Function

 <- function() {
}
