---
title: "Lab HW Assignment"
author: "Nicole Ayala"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE,
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```

###  Working with Intertidal data 

```{r}
# Load the Libraries
library(here)
library(tidyverse)
library(ggridges)
library(hrbrthemes)
library(RColorBrewer)
library(janitor)
```
```{r}
# Load the data
intertidal<-read_csv(here("Week_11","Data","intertidaldata.csv")) # mainly going to use this data set
lat<-read_csv(here("Week_11","Data","intertidaldata_latitude.csv"))
# read.csv reads everything as factors so I will be reading them in as characters with read_csv and change them accordingly to factors

```
### Clean the Data.Frame - Intertidal
- Mid 1
```{r}
intertidal %>%
  clean_names() # will clean any names that have misspellings or unnecessary numbers such as Mid 1
```
### Clean the Data
```{r}
intertidal_clean <- intertidal %>% 
   count(Site, sort = TRUE) %>% # sort the Algae in alphabetical order and then convert it into a factor to fix levels
   mutate(Site = factor(Site)) %>% # changing Small.barnacles into a factor and then changing it's name
    filter(Site %in% c("Crystal Cove", "Little Corona")) %>%
    droplevels() # drop the extra levels

intertidal_clean
 
``` 

### Reorder the Levels!!
```{r}
ordersbarn <- factor(c("Low", "Mid", "High"), levels = c("Low", "Mid", "High")) # reordering the levels to an order that makes sense!


ordersbarn
```
### Final Organziation of the Data Before Plotting
```{r}
glimpse(intertidal)
interplot <- intertidal %>% # changing the name of the df
   filter(Site %in% c("Crystal Cove", "Little Corona")) %>%
   mutate(Quadrat=factor(Quadrat,levels = c("Low", "Mid", "High"))) %>%
  group_by(Quadrat,`Small Barnacles`) %>% # grouping small barnacles and the quadrat together
  droplevels() # drop the extra levels
```
### Plotting Time
```{r}
ggplot(data = interplot, 
       aes(x= fct_reorder(Quadrat,`Small Barnacles`), # x axis (the factor)
           y = Site, # y axis
           fill = ("pink"))) +
  geom_density_ridges(show.legend = FALSE) + # wanted a density plot
  labs(title='Locations of Small Barnacles When at Various \n Tide Times', # chnages the title
       subtitle =' In ascending order: tides are shown as low, mid and high.', # changes the subtitle
       x='Quadrat', # the real x axis name
       y='Site',  # the real y axis name
       fill = "pink") +  # fill in density plot with pink color
   theme_minimal() + # minimla theme, no lines
   theme(panel.grid.major = element_blank(), # changes the size of all of the labs
        panel.grid.minor = element_blank()) +
  theme(plot.title = element_text(size = 20, hjust = 0.5, color ="cornsilk4"),
        plot.subtitle = element_text(size =15,hjust = 0.5, lineheight = 1.1, color = "cornsilk4"),
        axis.title = element_text(size=10,color = "black", hjust = 0.5), # title adjustments
        axis.text = element_text(size = 10,color = "black",hjust = 0.5), # text adjustments
        panel.grid = element_line(linewidth = 0.35, linetype = FALSE), # background gridlines
        plot.margin = unit(c(1.0, 1.0, 1.0, 1.0), "cm"), # margin adjustments
        plot.background = element_rect(color = "white"))
  
 ggsave(here("Week_11","Output","FactorPlot.png")) # save the plot!

```